### ISSUE TITLE
Java can't find .stg files in IntelliJ

### ISSUE THREAD

**Issue by shelbyspees** [antlr/jetbrains-plugin-st4#3]
I'm using IntelliJ 15, ANTLR4, ST4 on Windows 7. `PrettyPrint.stg` is in the same directory as `TestMain.java`.

When I moved everything to Cloud9 it worked fine.

```
"C:\Program Files\Java\jdk1.8.0_65\bin\java" . . .
Exception in thread "main" java.lang.IllegalArgumentException: No such group file: PrettyPrint.stg
	at org.stringtemplate.v4.STGroupFile.<init>(STGroupFile.java:69)
	at org.stringtemplate.v4.STGroupFile.<init>(STGroupFile.java:48)
	at ms3.TestMain.main(TestMain.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1
```

**Comment by parrt** [comment]
Well, without knowing what your ms3.TestMain.main does, I can help you. Anyway I don't think it has anything to do with plug-in as all it does is syntax highlight.
